# Generated by Django 3.1.4 on 2021-01-27 02:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ind_researcher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='project',
            name='researchers',
            field=models.ManyToManyField(blank=True, related_name='researchers', to='bio3.Profile'),
        ),
    ]
