# Generated by Django 3.1.4 on 2021-01-29 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bio3', '0002_auto_20210127_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bio3.university'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='websites',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
